import pyautogui
from time import sleep
nome = pyautogui.prompt(text='Digite seu nome',title='Coleta de Dados')
sobrenome = pyautogui.prompt(text='Digite seu sobrenome',title='Coleta de Dados')
email = pyautogui.prompt(text='Digite seu email',title='Coleta de Dados')
pyautogui.click(1463,176,duration=1)
pyautogui.typewrite(nome)
sleep(1)
pyautogui.click(1463,243,duration=1)
pyautogui.typewrite(sobrenome)
sleep(1)
pyautogui.click(1466,317,duration=1)
pyautogui.typewrite(email)
sleep(1)
captcha = pyautogui.locateCenterOnScreen('Captcha.PNG')
sleep(1)
pyautogui.click(captcha[0],captcha[1],duration=1)
sleep(1)
sumbit = pyautogui.locateCenterOnScreen('submit.PNG')
sleep(1)
pyautogui.click(sumbit[0],sumbit[1],duration=1)